// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmrpzerzzikxrwtetzcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcnB6ZXJ6emlreHJ3dGV0emNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTkzODEsImV4cCI6MjA3MjgzNTM4MX0.VjFcfPhod_q7Ap4vNN27BCd70vpilRBx2AzcTg7WlmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});